"""DIRTY ROOM: MK64 extracted assets -> games/mk64/spec (coarse facts only).

Reads the dirty tree after `make assets` + a full build (so the per-asset
JSON extractions under assets/ exist). Writes:
  spec/assets.json    every extracted file with its class (texture, incc,
                      tkmk00, audio, kept, derived, unhandled)
  spec/textures.json  per texture: fmt, size, colour grid, 2-bit alpha outline
  spec/samples.json   per tbl sample: size, loop, rate, coarse outline, f0
  spec/ci_groups.json palette -> frames (from the build's own n64graphics calls)
  spec/kept/...       user-approved facts copied verbatim (sequences, code/data
                      headers, geometry C, course metadata tables, ctl
                      structure with books and loop states zeroed)

    python -m games.mk64.extract_spec <pristine> <dirty> <spec dir>
"""
import collections
import glob
import json
import os
import re
import shutil
import struct
import subprocess
import sys

import numpy as np
import yaml

from cleanroom.gfx import png, texfmt
from cleanroom.decomp.spec import texture_fact
from cleanroom.decomp.census import walk
from cleanroom.audio import descriptor, vadpcm
from cleanroom.audio.pitch import median_f0
from games.mk64 import audiobank

FMT = {"rgba16": (texfmt.RGBA, texfmt.B16), "rgba32": (texfmt.RGBA, texfmt.B32), "ia16": (texfmt.IA, texfmt.B16),
       "ia8": (texfmt.IA, texfmt.B8), "ia4": (texfmt.IA, texfmt.B4), "i8": (texfmt.I, texfmt.B8),
       "i4": (texfmt.I, texfmt.B4), "ci8": (texfmt.CI, texfmt.B8), "ci4": (texfmt.CI, texfmt.B4),
       "tlut": (texfmt.RGBA, texfmt.B16)}
# derived from retail pixels, regenerated by the clean room (never kept)
DERIVED = ("wheel_masks/", "stitched_palettes/", ".export", "torch.hash.yml", ".assets-local.txt")


def incc_values(path):
    txt = open(path).read()
    return [int(v, 16) for v in re.findall(r"0x[0-9a-fA-F]+", txt)]


def yaml_textures(dirty):
    out = {}
    for f in glob.glob(os.path.join(dirty, "yamls/us/*.yml")):
        d = yaml.safe_load(open(f)) or {}
        for k, v in d.items():
            if isinstance(v, dict) and v.get("type") == "texture":
                out[v.get("symbol", k)] = v
                out.setdefault(k, v)                       # torch names some files by the yaml key
    return out


def incc_rgba(path, meta, ytex, dirty):
    fmt = os.path.basename(path).split(".")[-3]
    vals = incc_values(path)
    if "colors" in meta:                                   # a TLUT
        w, h = len(vals), 1                               # entries = what the data holds
    else:
        w, h = meta["width"], meta["height"]
    if fmt in ("rgba16", "tlut") or meta.get("ctype") == "u16":
        data = struct.pack(">%dH" % len(vals), *vals)
    else:
        data = bytes(vals)
    f, s = FMT[fmt]
    bits = texfmt.BITS[s]
    if len(data) * 8 // bits != w * h and "colors" not in meta:  # the data decides the row count
        h = max(1, len(data) * 8 // bits // w)
    pal = None
    if f == texfmt.CI and meta.get("tlut_symbol"):
        tp = glob.glob(os.path.join(dirty, "assets/code/*", meta["tlut_symbol"] + ".rgba16.inc.c"))
        if tp:
            tv = incc_values(tp[0])
            pal = texfmt.decode(struct.pack(">%dH" % len(tv), *tv), len(tv), 1, texfmt.RGBA, texfmt.B16)[0]
    if f == texfmt.CI and fmt == "ci8" and len(data) < w * h:
        data += bytes(w * h - len(data))
    return texfmt.decode(data, w, h, f, s, pal), fmt


def tkmk_alpha(dirty):
    """symbol -> alpha colour the game decodes it with (MenuTexture.type 1 -> 0xBE)."""
    src = open(os.path.join(dirty, "src/data/textures.c")).read()
    out = {}
    for t, sym in re.findall(r"\{\s*(\d+),\s*(\w+),", src):
        if int(t) == 1:
            out[sym] = 0xBE
        else:
            out.setdefault(sym, 1)
    return out


def tkmk_rgba(dirty, path, alpha):
    exe = os.path.join(dirty, "tools", "tkmk00.exe")
    tmp = path + ".raw.tmp"
    subprocess.run([exe, "-d", "-a", hex(alpha), path, tmp], check=True, capture_output=True)
    b = open(path, "rb").read()
    w, h = int.from_bytes(b[8:10], "big"), int.from_bytes(b[10:12], "big")
    raw = open(tmp, "rb").read()
    os.remove(tmp)
    return texfmt.decode(raw, w, h, texfmt.RGBA, texfmt.B16)


def ci_groups(dirty):
    """palette png -> frame pngs, from the build's own conversion commands."""
    env = dict(os.environ)
    r = subprocess.run(["make", "-n", "-B", "CC_CHECK=true", "NOEXTRACT=1"], cwd=dirty, capture_output=True,
                       text=True, env=env)
    groups = collections.defaultdict(list)
    for line in r.stdout.splitlines():
        if "n64graphics" not in line or " -p " not in line:
            continue
        g = re.search(r"-g (\S+)", line)
        p = re.search(r"-p (\S+)", line)
        fm = re.search(r" -f (\S+)", line)
        if g and p:
            groups[p.group(1)].append({"png": g.group(1), "fmt": fm.group(1) if fm else "ci8",
                                       "mask": "-M" in line})
    return {k: v for k, v in groups.items()}


def sample_facts(dirty):
    ctl = open(os.path.join(dirty, "bin/audiobanks.us.bin"), "rb").read()
    tbl = open(os.path.join(dirty, "bin/audiotables.bin"), "rb").read()
    S = audiobank.samples(ctl, tbl)
    out = {}
    for key, s in sorted(S.items()):
        book = audiobank.book_at(ctl, s["books"][0])
        nframes = s["size"] // 9 * 16
        pcm = vadpcm.decode(tbl[key:key + s["size"]], book, nframes).astype(np.float64)
        rate = 32000.0 * max(s["tunings"])
        d = {"size": s["size"], "nframes": nframes, "rate": round(rate, 1), "tunings": s["tunings"],
             "loop": [s["start"], s["end"], s["count"]], "books": s["books"], "loops": s["loops"],
             "refs": s["refs"], "desc": descriptor.describe(pcm, rate)}
        f0 = median_f0((pcm / 32768).astype(np.float32), rate)
        if f0:
            d["f0"] = round(f0, 1)
        out[str(key)] = d
    # kept ctl structure: books and loop states zeroed (they are derived from retail audio)
    c = bytearray(ctl)
    for s in S.values():
        for bo in s["books"]:
            order, npred = struct.unpack_from(">ii", c, bo)
            c[bo + 8:bo + 8 + 16 * order * npred] = bytes(16 * order * npred)
        for lo in s["loops"]:
            if s["count"]:
                c[lo + 16:lo + 48] = bytes(32)
    return out, bytes(c)


def main(argv):
    pristine, dirty, spec = argv[1], argv[2], argv[3]
    os.makedirs(os.path.join(spec, "kept"), exist_ok=True)
    added = sorted(walk(dirty, ["baserom"]) - walk(pristine, ["baserom"]))
    ytex = yaml_textures(dirty)
    alpha = tkmk_alpha(dirty)
    added_set = set(added)
    cls, tex, errors = {}, {}, []
    for i, a in enumerate(added):
        p = os.path.join(dirty, a)
        try:
            if a == "nul" or a.startswith(("modding/", "docs/")) or any(x in a for x in DERIVED) or a.endswith((".bin", ".mio0", ".raw")) and a.startswith("assets/"):
                cls[a] = "derived"
            elif a.startswith("textures/raw/ipl3_font_"):         # inside the IPL3 boot code (CIC checksum)
                dst = os.path.join(spec, "kept", a)
                os.makedirs(os.path.dirname(dst), exist_ok=True)
                shutil.copyfile(p, dst)
                cls[a] = "kept"
            elif a.endswith(".inc.c") and a[:-6] + ".png" in added_set:   # the build derives it from our PNG
                cls[a] = "derived"
            elif a.endswith(".png"):
                tex[a] = texture_fact(a, png.read(p))
                cls[a] = "texture"
            elif a.endswith(".inc.c") and os.path.basename(a).split(".")[-3] in FMT \
                    and os.path.basename(a).split(".")[0] in ytex:
                rgba, fmt = incc_rgba(p, ytex[os.path.basename(a).split(".")[0]], ytex, dirty)
                tex[a] = texture_fact(a, rgba)
                cls[a] = "incc"
            elif a.endswith(".tkmk00"):
                sym = os.path.basename(a).split(".")[0]
                al = alpha.get(sym, 1)
                tex[a] = texture_fact(a, tkmk_rgba(dirty, p, al))
                tex[a]["tk_alpha"] = al
                cls[a] = "tkmk00"
            elif a in ("bin/audiobanks.us.bin", "bin/audiotables.bin"):
                cls[a] = "audio"
            elif a.endswith((".m64", ".h", ".c", ".yml")) or a.startswith("bin/lib/"):
                dst = os.path.join(spec, "kept", a)
                os.makedirs(os.path.dirname(dst), exist_ok=True)
                shutil.copyfile(p, dst)
                cls[a] = "kept"
            else:
                cls[a] = "unhandled"
        except Exception as e:
            errors.append(f"{a}: {e!r}")
            cls[a] = "error"
        if i % 500 == 0:
            print(f"  {i}/{len(added)}", flush=True)
    smp, ctl = sample_facts(dirty)
    os.makedirs(os.path.join(spec, "kept", "bin"), exist_ok=True)
    open(os.path.join(spec, "kept", "bin", "audiobanks.us.bin"), "wb").write(ctl)
    tbl = open(os.path.join(dirty, "bin/audiotables.bin"), "rb").read()
    hdr_end = min(int(k) for k in smp)
    json.dump({"tbl_len": len(tbl), "tbl_header": tbl[:hdr_end].hex()},
              open(os.path.join(spec, "tbl_layout.json"), "w"))
    groups = ci_groups(dirty)
    json.dump({"assets": cls}, open(os.path.join(spec, "assets.json"), "w"), indent=0)
    json.dump(tex, open(os.path.join(spec, "textures.json"), "w"), separators=(",", ":"))
    json.dump(smp, open(os.path.join(spec, "samples.json"), "w"), separators=(",", ":"))
    json.dump(groups, open(os.path.join(spec, "ci_groups.json"), "w"), indent=0)
    c = collections.Counter(cls.values())
    print(f"spec: {dict(c)}; {len(smp)} samples; {len(groups)} ci groups "
          f"({sum(len(v) for v in groups.values())} frames) -> {spec}")
    un = [a for a, k in cls.items() if k == "unhandled"]
    if un:
        print("  unhandled:", collections.Counter(os.path.splitext(u)[1] for u in un).most_common(8), un[:5])
    for e in errors[:8]:
        print("  ERROR", e)


if __name__ == "__main__":
    main(sys.argv)
